import { chromium } from '@playwright/test';
const browser = await chromium.launch({channel:'chrome',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/demo');
await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();
await page.screenshot({path:'desktop-check.png',fullPage:true});
await page.getByRole('button',{name:'View all leads'}).click();
await page.getByPlaceholder('Search leads...').fill('Blue Bottle');
await page.getByRole('button',{name:/Blue Bottle Coffee bluebottlecoffee.com/}).click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('link',{name:'Lead lists',exact:true}).click();
await page.getByRole('button',{name:'Create list',exact:true}).click();
await page.getByPlaceholder('e.g. Austin coffee shops').fill('Browser test collection');
await page.getByRole('dialog').getByRole('button',{name:'Create list'}).click();
await page.getByRole('heading',{name:'Browser test collection'}).waitFor();
await page.getByRole('link',{name:'All leads'}).click();
await page.getByRole('button',{name:'Export',exact:true}).click();
const downloaded=page.waitForEvent('download');
await page.getByRole('button',{name:/Excel workbook/}).click();
const file=await downloaded;if(!file.suggestedFilename().endsWith('.xlsx'))throw new Error('Excel export failed');
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:5173/demo');
await page.getByRole('heading',{name:'Overview',exact:true}).waitFor();
await page.screenshot({path:'mobile-check.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile viewport overflow');
await page.getByRole('button',{name:'Toggle navigation'}).click();
await page.getByRole('link',{name:'Settings',exact:true}).click();
await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();
await browser.close();
if(errors.length)throw new Error(errors.join('\n'));
console.log('Browser checks passed: dashboard, search, details, lists, Excel download, mobile navigation and overflow.');
