import { useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import Papa from 'papaparse';
import { BriefcaseBusiness, Building2, CalendarDays, Check, CloudDownload, Eye, ExternalLink, FileUp, Globe2, Layers3, Mail, MailSearch, MapPin, Plus, RefreshCw, Search, Send, Trash2, X } from 'lucide-react';
import { api, type Page } from './api';
import './jobs.css';

type Job = {
  id:number; source_platform:string; source_job_id?:string|null; source_url?:string|null; title:string;
  company_name?:string|null; company_website?:string|null; company_domain?:string|null; location?:string|null; country?:string|null;
  workplace_type?:string|null; employment_type?:string|null; seniority_level?:string|null;
  salary_min?:number|null; salary_max?:number|null; salary_currency?:string|null; salary_period?:string|null;
  description?:string|null; requirements?:string|null; contact_name?:string|null; contact_email?:string|null; email_discovery_status?:string;
  status:string; posted_at?:string|null; expires_at?:string|null; created_at:string; metadata?:Record<string,unknown>|null;
  trust_score:number; risk_level:'low'|'review'|'high'; risk_reasons:string[]; opportunity_score:number;
};
type FilterValue={source_platform?:string;country?:string;workplace_type?:string;total:number};
type SyncRun={id:number;status:string;created_count:number;updated_count:number;failed_count:number;started_at:string;finished_at?:string|null};
type Filters={sources:FilterValue[];countries:FilterValue[];workplace_types:FilterValue[];statuses:string[];with_email:number;with_domain:number;latest_sync?:SyncRun|null};
type WorkerRequest={id:number;type:'scrape'|'enrich';status:'pending'|'running'|'completed'|'failed';error?:string|null;created_at:string};
type JobGroup={id:number;name:string;countries:string[];jobs_count:number};
type CountryOption={country:string;total:number;with_email:number};

const statuses=['new','saved','applied','interview','rejected','closed'];
const label=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const date=(value?:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value)):'Not provided';
const plainText=(value:string)=>new DOMParser().parseFromString(value,'text/html').body.textContent||'';

export function Jobs({workspaceId,onNavigate}:{workspaceId:number;onNavigate?:(tab:string)=>void}){
 const cache=useQueryClient();
 const [page,setPage]=useState(1),[perPage,setPerPage]=useState(15),[search,setSearch]=useState(''),[source,setSource]=useState(''),[country,setCountry]=useState(''),[workplace,setWorkplace]=useState(''),[status,setStatus]=useState(''),[emailStatus,setEmailStatus]=useState('');
 const [viewing,setViewing]=useState<Job|null>(null),[creating,setCreating]=useState(false),[importing,setImporting]=useState(false),[creatingGroup,setCreatingGroup]=useState(false),[deleting,setDeleting]=useState<Job|null>(null),[deletingAll,setDeletingAll]=useState(false);
 const [notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const params=useMemo(()=>new URLSearchParams({page:String(page),per_page:String(perPage),...(search&&{q:search}),...(source&&{source}),...(country&&{country}),...(workplace&&{workplace_type:workplace}),...(status&&{status}),...(emailStatus&&{email_status:emailStatus})}).toString(),[page,perPage,search,source,country,workplace,status,emailStatus]);
 const jobs=useQuery({queryKey:['jobs',workspaceId,params],queryFn:()=>api<Page<Job>>(`/workspaces/${workspaceId}/jobs?${params}`),enabled:!!workspaceId});
 const filters=useQuery({queryKey:['job-filters',workspaceId],queryFn:()=>api<Filters>(`/workspaces/${workspaceId}/jobs/filters`),enabled:!!workspaceId});
 const worker=useQuery({queryKey:['job-worker',workspaceId],queryFn:()=>api<{requests:WorkerRequest[]}>(`/workspaces/${workspaceId}/jobs/worker-status`),enabled:!!workspaceId,refetchInterval:q=>q.state.data?.requests.some(r=>r.status==='pending'||r.status==='running')?3000:15000});
 const groups=useQuery({queryKey:['campaign-groups',workspaceId],queryFn:()=>api<{groups:JobGroup[];countries:CountryOption[]}>(`/workspaces/${workspaceId}/campaign-audience-groups`),enabled:!!workspaceId});
 const refresh=async()=>Promise.all([cache.invalidateQueries({queryKey:['jobs',workspaceId]}),cache.invalidateQueries({queryKey:['job-filters',workspaceId]})]);
 const clear=()=>{setSearch('');setSource('');setCountry('');setWorkplace('');setStatus('');setEmailStatus('');setPage(1)};

 async function changeStatus(job:Job,next:string){setError('');try{await api(`/workspaces/${workspaceId}/jobs/${job.id}`,'PATCH',{status:next});await refresh()}catch(e){setError((e as Error).message)}}
 async function remove(){if(!deleting)return;setBusy(true);setError('');try{await api(`/workspaces/${workspaceId}/jobs/${deleting.id}`,'DELETE');setDeleting(null);setViewing(null);setNotice('Job removed from the workspace.');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function removeAll(){setBusy(true);setError('');try{const result=await api<{deleted:number}>(`/workspaces/${workspaceId}/jobs`,'DELETE');setDeletingAll(false);setPage(1);setNotice(`${result.deleted} jobs permanently deleted.`);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function sync(){setBusy(true);setError('');setNotice('');try{const result=await api<SyncRun>(`/workspaces/${workspaceId}/jobs/sync`,'POST');setNotice(`Daily feeds synced: ${result.created_count} new Ãƒâ€šÃ‚Â· ${result.updated_count} refreshed Ãƒâ€šÃ‚Â· ${result.failed_count} failed`);setPage(1);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function enrich(){setBusy(true);setError('');setNotice('');try{const result=await api<{checked:number;found:number}>(`/workspaces/${workspaceId}/jobs/enrich`,'POST');setNotice(`Checked ${result.checked} employer websites Ãƒâ€šÃ‚Â· found ${result.found} public emails`);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}

 async function queueWorker(type:'scrape'|'enrich'){setBusy(true);setError('');setNotice('');try{await api(`/workspaces/${workspaceId}/jobs/worker-requests`,'POST',{type});setNotice(type==='scrape'?'EC2 scraper queued. Jobs will appear automatically.':'EC2 email discovery queued.');await worker.refetch()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveGroup(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await api(`/workspaces/${workspaceId}/campaign-audience-groups`,'POST',{name:form.get('name'),countries:form.getAll('countries'),require_email:true});setCreatingGroup(false);setNotice('Job application group created.');await groups.refetch()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function deleteGroup(group:JobGroup){if(!confirm(`Delete ${group.name}?`))return;setError('');try{await api(`/workspaces/${workspaceId}/campaign-audience-groups/${group.id}`,'DELETE');setNotice('Job application group deleted.');await groups.refetch()}catch(e){setError((e as Error).message)}}
 const activeWorker=worker.data?.requests.find(r=>r.status==='pending'||r.status==='running');
 const latestWorker=worker.data?.requests[0];

 return <div className="jobs-page">
  <div className="jobs-actions"><button className="button" disabled={!groups.data?.countries.length} onClick={()=>setCreatingGroup(true)}><Layers3 size={16}/>Create job group</button><button className="button primary" disabled={busy||!!activeWorker} onClick={()=>queueWorker('scrape')}><CloudDownload size={16}/>Run EC2 scraper</button><button className="button" disabled={busy||!!activeWorker} onClick={()=>queueWorker('enrich')}><MailSearch size={16}/>Find job emails</button><button className="button" disabled={busy} onClick={sync}><RefreshCw size={16} className={busy?'spin':''}/>Sync free feeds</button><button className="button" onClick={()=>setImporting(true)}><FileUp size={16}/>Import jobs</button><button className="button" onClick={()=>setCreating(true)}><Plus size={16}/>Add job</button><button className="button danger" disabled={busy||!jobs.data?.total} onClick={()=>setDeletingAll(true)}><Trash2 size={16}/>Delete all</button></div>
  {notice&&<div className="platform-notice"><Check size={15}/>{notice}<button className="notice-close" onClick={()=>setNotice('')}><X size={14}/></button></div>}
  {error&&<div className="platform-error">{error}</div>}
  {latestWorker&&<div className={`job-sync-note worker-${latestWorker.status}`}><CloudDownload size={14}/><strong>EC2 worker:</strong> {label(latestWorker.type)} is {latestWorker.status}.{latestWorker.status==='completed'?' Results are saved in this workspace.':''}{latestWorker.error?` ${latestWorker.error}`:''}</div>}
  <section className="jobs-summary">
   <article><BriefcaseBusiness size={22}/><span><strong>{jobs.data?.total||0}</strong>Total jobs</span></article>
   <article><Building2 size={22}/><span><strong>{filters.data?.sources.length||0}</strong>Connected sources</span></article>
   <article><Globe2 size={22}/><span><strong>{filters.data?.with_domain||0}</strong>Company domains</span></article>
   <article><Mail size={22}/><span><strong>{filters.data?.with_email||0}</strong>Published emails</span></article>
  </section>
  <section className="job-groups-panel"><div className="job-groups-heading"><div><h2>Job application groups</h2><p>Reusable groups of unapplied jobs with contact emails, filtered by country.</p></div><button className="button" disabled={!groups.data?.countries.length} onClick={()=>setCreatingGroup(true)}><Plus size={15}/>New group</button></div>{groups.isPending?<div className="job-group-empty">Loading job groups…</div>:groups.data?.groups.length?<div className="job-group-grid">{groups.data.groups.map(group=><article key={group.id}><div><span><Layers3 size={17}/></span><button className="icon-button" aria-label={`Delete ${group.name}`} onClick={()=>deleteGroup(group)}><Trash2 size={14}/></button></div><h3>{group.name}</h3><p>{group.countries.join(', ')}</p><strong>{group.jobs_count.toLocaleString()} eligible jobs</strong><button className="button compact" onClick={()=>onNavigate?.('Campaigns')}><Send size={13}/>Create campaign</button></article>)}</div>:<div className="job-group-empty">No groups yet. Create one from countries that have unapplied jobs with email addresses.</div>}</section>
  <div className="job-sync-note"><RefreshCw size={14}/>Automatic sync runs daily at 2:15 AM. {filters.data?.latest_sync?`Last sync: ${date(filters.data.latest_sync.started_at)} Ãƒâ€šÃ‚Â· ${filters.data.latest_sync.created_count} new jobs.`:'Run the first sync to load free job feeds.'}</div>
  <div className="jobs-toolbar">
   <label className="platform-search"><Search size={17}/><input aria-label="Search jobs" placeholder="Search title, company, or location..." value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label>
   <select aria-label="Source" value={source} onChange={e=>{setSource(e.target.value);setPage(1)}}><option value="">All sources</option>{filters.data?.sources.map(v=><option key={v.source_platform} value={v.source_platform}>{v.source_platform} ({v.total})</option>)}</select>
   <select aria-label="Country" value={country} onChange={e=>{setCountry(e.target.value);setPage(1)}}><option value="">All countries</option>{filters.data?.countries.map(v=><option key={v.country} value={v.country}>{v.country} ({v.total})</option>)}</select>
   <select aria-label="Workplace type" value={workplace} onChange={e=>{setWorkplace(e.target.value);setPage(1)}}><option value="">All workplace types</option>{filters.data?.workplace_types.map(v=><option key={v.workplace_type} value={v.workplace_type}>{label(v.workplace_type||'unknown')} ({v.total})</option>)}</select>
   <select aria-label="Application status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{statuses.map(v=><option key={v} value={v}>{label(v)}</option>)}</select>
   <select aria-label="Email availability" value={emailStatus} onChange={e=>{setEmailStatus(e.target.value);setPage(1)}}><option value="">All email results</option><option value="with_email">With email</option><option value="without_email">Without email</option></select>
   {(search||source||country||workplace||status||emailStatus)&&<button className="button" onClick={clear}>Clear</button>}
  </div>
  <section className="platform-card jobs-table-card">
   {jobs.isLoading?<div className="jobs-loading">Loading jobsÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦</div>:jobs.isError?<div className="platform-empty"><h2>Jobs could not be loaded</h2><p>{(jobs.error as Error).message}</p><button className="button" onClick={()=>jobs.refetch()}>Try again</button></div>:jobs.data?.data.length?<>
    <div className="table-scroll"><table className="platform-table jobs-table"><thead><tr><th>Job</th><th>Source</th><th>Location</th><th>Quality</th><th>Data received</th><th>Status</th><th>Actions</th></tr></thead><tbody>{jobs.data.data.map(job=><tr key={job.id}>
     <td><strong>{job.title}</strong><small className="cell-subtitle">{job.company_name||'Company not provided'}{job.employment_type?` Ãƒâ€šÃ‚Â· ${job.employment_type}`:''}</small><span className="job-enrichment">{job.company_domain&&<span><Globe2 size={11}/>{job.company_domain}</span>}{job.contact_email&&<span className="has-email"><Mail size={11}/>Email found</span>}</span></td>
     <td><span className="job-source">{job.source_platform}</span></td>
     <td className="job-location">{job.location||job.country||'Not provided'}<small className="cell-subtitle">{label(job.workplace_type||'unknown')}</small></td>
     <td><div className="job-score"><strong>{job.trust_score}</strong><span className={`risk-${job.risk_level}`}>{label(job.risk_level)} risk</span><small>{job.opportunity_score}% opportunity</small></div></td>
     <td>{date(job.created_at)}<small className="cell-subtitle">Posted {date(job.posted_at)}</small></td>
     <td><select className={`job-status ${job.status}`} aria-label={`Status for ${job.title}`} value={job.status} onChange={e=>changeStatus(job,e.target.value)}>{statuses.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></td>
     <td><div className="row-actions"><button className="icon-button" aria-label={`View ${job.title}`} onClick={()=>setViewing(job)}><Eye size={16}/></button>{job.source_url&&<a className="icon-button" aria-label="Open source listing" href={job.source_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a>}<button className="icon-button" aria-label={`Delete ${job.title}`} onClick={()=>setDeleting(job)}><Trash2 size={16}/></button></div></td>
    </tr>)}</tbody></table></div>
    <div className="platform-pagination"><span>Showing {((jobs.data.current_page-1)*perPage+1).toLocaleString()}ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“{Math.min(jobs.data.current_page*perPage,jobs.data.total).toLocaleString()} of {jobs.data.total.toLocaleString()} Ãƒâ€šÃ‚Â· Page {jobs.data.current_page} of {jobs.data.last_page}</span><div><select value={perPage} onChange={e=>{setPerPage(Number(e.target.value));setPage(1)}}><option value="15">15 per page</option><option value="30">30 per page</option><option value="50">50 per page</option></select><button className="button" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><button className="button" disabled={page>=jobs.data.last_page} onClick={()=>setPage(page+1)}>Next</button></div></div>
   </>:<div className="platform-empty"><span><BriefcaseBusiness size={27}/></span><h2>No jobs found</h2><p>{search||source||country||workplace||status||emailStatus?'No jobs match these filters.':'Add a job or import a CSV from any job platform to begin.'}</p><button className="button primary" onClick={()=>setImporting(true)}><FileUp size={16}/>Import jobs</button></div>}
  </section>
  {creatingGroup&&<Modal title="Create job application group" close={()=>!busy&&setCreatingGroup(false)}><form className="platform-form" onSubmit={saveGroup}><label>Group name<input name="name" required maxLength={120} placeholder="Remote jobs — US and Canada"/></label><label>Countries<select name="countries" multiple required size={Math.min(9,Math.max(3,groups.data?.countries.length||3))}>{groups.data?.countries.map(country=><option key={country.country} value={country.country}>{country.country} — {country.with_email} eligible jobs</option>)}</select><small>Hold Ctrl on Windows or Command on Mac to select multiple countries.</small></label><div className="email-consent-note"><Mail size={17}/><p>Only unapplied jobs with contact emails are included. Successfully emailed jobs and addresses are removed from future campaigns.</p></div>{error&&<div className="platform-error">{error}</div>}<div className="dialog-actions"><button type="button" className="button" onClick={()=>setCreatingGroup(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Creating…':'Create job group'}</button></div></form></Modal>}
  {creating&&<JobForm close={()=>setCreating(false)} save={async data=>{setBusy(true);setError('');try{await api(`/workspaces/${workspaceId}/jobs`,'POST',data);setCreating(false);setNotice('Job saved to your workspace.');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}} busy={busy} error={error}/>}
  {importing&&<JobImporter close={()=>setImporting(false)} busy={busy} error={error} run={async(sourceName,rows)=>{setBusy(true);setError('');try{const result=await api<{created:number;updated:number;failed:number}>(`/workspaces/${workspaceId}/jobs/import`,'POST',{source_platform:sourceName,jobs:rows});setImporting(false);setNotice(`${result.created} jobs added Ãƒâ€šÃ‚Â· ${result.updated} updated Ãƒâ€šÃ‚Â· ${result.failed} failed`);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/>}
  {viewing&&<JobDetails job={viewing} close={()=>setViewing(null)}/>}
  {deleting&&<Modal title="Delete job?" close={()=>!busy&&setDeleting(null)}><p><strong>{deleting.title}</strong> will be permanently removed from this workspace.</p>{error&&<div className="platform-error">{error}</div>}<div className="dialog-actions"><button className="button" onClick={()=>setDeleting(null)}>Cancel</button><button className="button danger" disabled={busy} onClick={remove}>{busy?'DeletingÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦':'Delete job'}</button></div></Modal>}
  {deletingAll&&<Modal title="Delete every job?" close={()=>!busy&&setDeletingAll(false)}><p>All <strong>{jobs.data?.total.toLocaleString()||0}</strong> jobs in this workspace will be permanently deleted.</p><p>This action cannot be undone.</p>{error&&<div className="platform-error">{error}</div>}<div className="dialog-actions"><button className="button" disabled={busy} onClick={()=>setDeletingAll(false)}>Cancel</button><button className="button danger" disabled={busy} onClick={removeAll}>{busy?'DeletingÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦':'Delete all permanently'}</button></div></Modal>}
 </div>
}

function JobForm({close,save,busy,error}:{close:()=>void;save:(data:Record<string,unknown>)=>void;busy:boolean;error:string}){
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));save(Object.fromEntries(Object.entries(raw).filter(([,v])=>v!=='')))}
 return <Modal title="Add a job" close={close}><form className="platform-form" onSubmit={submit}><div className="form-two"><label>Job title<input name="title" required maxLength={255}/></label><label>Source platform<input name="source_platform" required placeholder="Indeed, LinkedIn, UpworkÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦" maxLength={100}/></label><label>Company<input name="company_name" maxLength={255}/></label><label>Source URL<input name="source_url" type="url" placeholder="https://ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦"/></label><label>Contact name<input name="contact_name" maxLength={255} placeholder="Hiring manager or recruiter"/></label><label>Contact email<input name="contact_email" type="email" maxLength={255} autoComplete="email" placeholder="recruiter@company.com"/></label><label>Location<input name="location" maxLength={255}/></label><label>Country<input name="country" maxLength={100}/></label><label>Workplace type<select name="workplace_type" defaultValue="unknown"><option value="unknown">Unknown</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">Onsite</option></select></label><label>Employment type<input name="employment_type" placeholder="Full-time, ContractÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦"/></label><label>Posted date<input name="posted_at" type="date"/></label><label>Status<select name="status" defaultValue="new">{statuses.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label></div><label>Description<textarea name="description" rows={7}/></label>{error&&<div className="platform-error">{error}</div>}<div className="dialog-actions"><button type="button" className="button" onClick={close}>Cancel</button><button className="button primary" disabled={busy}>{busy?'SavingÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦':'Save job'}</button></div></form></Modal>
}

function JobImporter({close,run,busy,error}:{close:()=>void;run:(source:string,rows:Record<string,unknown>[])=>void;busy:boolean;error:string}){
 const file=useRef<HTMLInputElement>(null),[source,setSource]=useState('Indeed'),[rows,setRows]=useState<Record<string,unknown>[]>([]),[localError,setLocalError]=useState('');
 function selectFile(input:File){Papa.parse<Record<string,unknown>>(input,{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),complete:r=>{if(r.errors.length&&!r.data.length){setLocalError(r.errors[0].message);return}setRows(r.data);setLocalError('')}})}
 return <Modal title="Import jobs from CSV" close={close}><div className="job-import-help"><FileUp size={22}/><div><strong>Use an export from any job source</strong><p>Recognized fields include title/job_title, company, location, job_url, job_id, description, posted_at, workplace_type, and salary fields.</p></div></div><form className="platform-form" onSubmit={e=>{e.preventDefault();if(!rows.length){setLocalError('Choose a CSV containing at least one job.');return}run(source,rows)}}><label>Source platform<input value={source} onChange={e=>setSource(e.target.value)} required placeholder="Indeed"/></label><label>CSV file<input ref={file} type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&selectFile(e.target.files[0])}/></label>{rows.length>0&&<div className="platform-notice"><Check size={15}/>{rows.length.toLocaleString()} rows ready to import</div>}{(localError||error)&&<div className="platform-error">{localError||error}</div>}<div className="dialog-actions"><button type="button" className="button" onClick={close}>Cancel</button><button className="button primary" disabled={busy||!rows.length}>{busy?'ImportingÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦':`Import ${rows.length||''} jobs`}</button></div></form></Modal>
}

function JobDetails({job,close}:{job:Job;close:()=>void}){
 const salary=job.salary_min||job.salary_max?`${job.salary_currency||''} ${job.salary_min?.toLocaleString()||'ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â'} ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Å“ ${job.salary_max?.toLocaleString()||'ÃƒÂ¢Ã¢â€šÂ¬Ã¢â‚¬Â'}${job.salary_period?` / ${job.salary_period}`:''}`:'Not provided';
 return <Modal title="Job details" close={close}><div className="job-detail-head"><span><BriefcaseBusiness size={25}/></span><div><h2>{job.title}</h2><p>{job.company_name||'Company not provided'}</p></div>{job.source_url&&<a className="button" href={job.source_url} target="_blank" rel="noreferrer">View listing <ExternalLink size={14}/></a>}</div><JobAssessment job={job}/><div className="job-detail-grid"><Info icon={<Building2/>} title="Source" value={job.source_platform}/><Info icon={<MapPin/>} title="Location" value={[job.location,job.country].filter(Boolean).join(', ')||'Not provided'}/><Info icon={<CalendarDays/>} title="Posted" value={date(job.posted_at)}/><Info icon={<BriefcaseBusiness/>} title="Employment" value={[label(job.workplace_type||'unknown'),job.employment_type,job.seniority_level].filter(Boolean).join(' Ãƒâ€šÃ‚Â· ')}/><Info title="Salary" value={salary}/><Info icon={<Globe2/>} title="Company domain" value={job.company_domain||'Not found'}/><Info icon={<Mail/>} title="Published contact email" value={job.contact_email||'Not found'}/><Info title="Email discovery" value={label(job.email_discovery_status||'not checked')}/></div>{job.description&&<section className="job-copy"><h3>Description</h3><p>{plainText(job.description)}</p></section>}{job.requirements&&<section className="job-copy"><h3>Requirements</h3><p>{job.requirements}</p></section>}</Modal>
}
function JobAssessment({job}:{job:Job}){return <><section className="job-assessment"><div><small>Trust score</small><strong>{job.trust_score}/100</strong><span className={`risk-${job.risk_level}`}>{label(job.risk_level)} scam risk</span></div><div><small>Estimated opportunity</small><strong>{job.opportunity_score}%</strong><span>Based on listing quality and freshness</span></div><ul>{job.risk_reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section><p className="score-note">Automated indicators are not guarantees. Verify the employer before sharing personal or payment information.</p></>}function Info({icon,title,value}:{icon?:ReactNode;title:string;value:string}){return <div className="job-info">{icon&&<span>{icon}</span>}<small>{title}</small><strong>{value}</strong></div>}
function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){return <dialog className="platform-dialog jobs-dialog" ref={el=>{if(el&&!el.open)el.showModal()}} onCancel={e=>{e.preventDefault();close()}}><div className="modal-header"><h2>{title}</h2><button aria-label="Close dialog" className="icon-button" onClick={close}><X size={20}/></button></div>{children}</dialog>}
