import { useState, type FormEvent } from 'react';
import { Check, CreditCard, ShieldCheck } from 'lucide-react';
import { api } from './api';

export type StripeSettings = {mode:'test'|'live';automatic_tax:boolean;frontend_url:string;has_secret:boolean;has_webhook_secret:boolean;secret_source:string|null;webhook_url:string};

export function StripeAdmin({settings,onSaved}:{settings:StripeSettings;onSaved:(value:StripeSettings)=>void}){
 const[busy,setBusy]=useState(false),[testing,setTesting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const form=e.currentTarget,f=new FormData(form);try{const next=await api<StripeSettings>('/admin/stripe','PATCH',{mode:f.get('mode'),secret:f.get('secret')||null,webhook_secret:f.get('webhook_secret')||null,automatic_tax:f.get('automatic_tax')==='on',frontend_url:f.get('frontend_url'),remove_secret:f.get('remove_secret')==='on',remove_webhook_secret:f.get('remove_webhook_secret')==='on'});onSaved(next);(form.elements.namedItem('secret') as HTMLInputElement).value='';(form.elements.namedItem('webhook_secret') as HTMLInputElement).value='';setNotice('Stripe settings saved securely.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function test(){setTesting(true);setError('');setNotice('');try{const result=await api<{account_id:string;charges_enabled:boolean}>('/admin/stripe/test','POST');setNotice(`Connected to ${result.account_id}. ${result.charges_enabled?'Charges are enabled.':'Stripe has not enabled charges for this account yet.'}`)}catch(e){setError((e as Error).message)}finally{setTesting(false)}}
 return <div className="stripe-admin-grid"><form className="platform-card platform-form stripe-admin-form" onSubmit={save}><div className="platform-card-heading"><div><h2>Stripe gateway</h2><p>Manage payment credentials and checkout behavior.</p></div><span className={`state-pill ${settings.has_secret&&settings.has_webhook_secret?'':'paused'}`}>{settings.has_secret&&settings.has_webhook_secret?'Configured':'Setup required'}</span></div>{error&&<div className="platform-error">{error}</div>}{notice&&<div className="platform-notice"><Check size={15}/>{notice}</div>}<label>Mode<select name="mode" defaultValue={settings.mode}><option value="test">Test mode</option><option value="live">Live mode</option></select></label><label>Stripe secret key <small>{settings.has_secret?`Saved (${settings.secret_source})`:'Not configured'}</small><input name="secret" type="password" autoComplete="new-password" placeholder={settings.mode==='live'?'sk_live_...':'sk_test_...'}/></label>{settings.has_secret&&<label className="stripe-check"><input type="checkbox" name="remove_secret"/> Remove saved secret key</label>}<label>Webhook signing secret <small>{settings.has_webhook_secret?'Saved securely':'Not configured'}</small><input name="webhook_secret" type="password" autoComplete="new-password" placeholder="whsec_..."/></label>{settings.has_webhook_secret&&<label className="stripe-check"><input type="checkbox" name="remove_webhook_secret"/> Remove saved webhook secret</label>}<label>Application URL<input name="frontend_url" type="url" defaultValue={settings.frontend_url} required/></label><label className="stripe-check"><input name="automatic_tax" type="checkbox" defaultChecked={settings.automatic_tax}/> Enable Stripe automatic tax</label><div className="dialog-actions"><button className="button" type="button" disabled={!settings.has_secret||testing||busy} onClick={test}>{testing?'Testing…':'Test connection'}</button><button className="button primary" disabled={busy}>{busy?'Saving…':'Save Stripe settings'}</button></div></form><aside className="platform-card stripe-admin-help"><span><ShieldCheck size={24}/></span><h2>Secrets stay private</h2><p>Keys are encrypted using the application key. Saved values are never sent back to the browser or written to the audit log.</p><h3>Webhook endpoint</h3><code>{settings.webhook_url}</code><p>Register this endpoint in Stripe for subscription and invoice events.</p><h3>Plan prices</h3><p>Configure each paid plan’s monthly and yearly Price IDs under the Plans tab.</p><CreditCard size={36}/></aside></div>
}
